version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    environment:
      NODE_ENV: production

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"