services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    networks:
      - app-network
    environment:
      NODE_ENV: development
    tty: true

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - app-network
    tty: true

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: